# Generated by Django 3.2 on 2022-04-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_setlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='gig',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appone.gig'),
        ),
        migrations.AddField(
            model_name='setlist',
            name='song',
            field=models.ManyToManyField(to='appone.Song'),
        ),
    ]
